<?php

namespace App\Domains\Billing\Actions;

use App\Domains\Billing\Models\Invoice;
use App\Domains\Billing\Models\Payment;
use App\Domains\Notification\Actions\SendNotification;
use App\Domains\Quotation\Actions\ConvertQuotationToCsns;
use App\Domains\Quotation\Models\Quotation;
use App\Domains\Quotation\Models\QuotationStatusLog;
use App\Enums\BillingStatus;
use App\Enums\DocumentType;
use App\Enums\InvoiceStatus;
use App\Enums\OrderType;
use App\Enums\QuotationStatus;
use App\Models\User;
use App\Services\DocumentNumberingService;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use InvalidArgumentException;
use Throwable;

/**
 * Section G + H: after payment completes or Admin releases the order, issue the billing documents and then
 * — only on success — create the CSN(s) with status "Pending Lorry Assignment". Failure keeps the order in
 * "Billing Generation Failed" and never creates a CSN; retry never duplicates an existing document.
 *
 * - Cash: one Cash Bill per completed payment transaction, before the CSN.
 * - COD: no invoice up front; the COD invoice is issued once the order is fully paid (issueInvoice, called
 *   from RefreshOrderPaidAmount after every payment change).
 * - Term (credit): no invoice up front; Admin generates the invoice whenever they want after the CSN
 *   (e.g. once the CSN is returned) with issueInvoice.
 */
class GenerateOrderBilling
{
    public function __construct(
        private DocumentNumberingService $numbering,
        private ConvertQuotationToCsns $convert,
        private SendNotification $notify,
    ) {}

    /** @return array{ok: bool, error: ?string, invoices: Collection<int, Invoice>, csns: Collection} */
    public function execute(Quotation $quotation, ?User $actor = null): array
    {
        $quotation->loadMissing(['customer', 'branch', 'lines', 'destinations', 'invoices', 'proformaInvoice']);
        $actor ??= User::query()->role('hq_admin')->first();

        if ($quotation->status === QuotationStatus::Converted && $quotation->billingStatus() === BillingStatus::Generated) {
            return ['ok' => true, 'error' => null, 'invoices' => $quotation->invoices, 'csns' => $quotation->consignmentNotes()->get()];
        }

        if (! $quotation->isEligibleForBilling()) {
            throw new InvalidArgumentException($quotation->billingBlockReason() ?? 'Order is not eligible for billing.');
        }

        try {
            $result = DB::transaction(function () use ($quotation, $actor) {
                $invoices = match ($quotation->orderType()) {
                    OrderType::Cash => $this->cashBills($quotation),
                    // a COD order already paid in full gets its invoice now; otherwise once fully paid
                    OrderType::Cod => $this->isFullyPaid($quotation) ? $this->invoice($quotation) : collect(),
                    OrderType::Term => collect(),
                    default => $this->invoice($quotation),
                };

                $quotation->update([
                    'billing_status' => BillingStatus::Generated,
                    'billing_error' => null,
                    'billed_at' => now(),
                ]);

                QuotationStatusLog::query()->create([
                    'quotation_id' => $quotation->id,
                    'from_status' => $quotation->status->value,
                    'to_status' => $quotation->status->value,
                    'user_id' => $actor?->id,
                    'remarks' => $invoices->isNotEmpty()
                        ? 'Billing issued: '.$invoices->pluck('number')->implode(', ')
                        : ($quotation->orderType() === OrderType::Term
                            ? 'Released for CSN · the invoice is generated by Admin later'
                            : 'Released for CSN · the COD invoice is issued once the order is fully paid'),
                ]);

                // Only after billing succeeded: create the CSN(s)
                $csns = $quotation->consignmentNotes()->exists()
                    ? $quotation->consignmentNotes()->get()
                    : $this->convert->execute(
                        $quotation->fresh(['customer', 'branch', 'lines', 'destinations', 'invoices', 'proformaInvoice']),
                        $actor,
                        $quotation->orderType()?->billingType()->value ?? 'cash_bill',
                    );

                // Link the billing documents to the (first) CSN for the legacy CSN views
                $firstCsn = $csns->first();

                if ($firstCsn) {
                    foreach ($invoices as $invoice) {
                        if (! $invoice->consignment_note_id) {
                            $invoice->update(['consignment_note_id' => $firstCsn->id]);
                            $invoice->lines()->whereNull('consignment_note_id')->update(['consignment_note_id' => $firstCsn->id]);
                        }
                    }

                    if ($quotation->proformaInvoice && ! $quotation->proformaInvoice->consignment_note_id) {
                        $quotation->proformaInvoice->update(['consignment_note_id' => $firstCsn->id]);
                    }

                    Payment::query()->where('quotation_id', $quotation->id)->whereNull('consignment_note_id')
                        ->update(['consignment_note_id' => $firstCsn->id]);
                }

                return ['invoices' => $invoices, 'csns' => $csns];
            });
        } catch (Throwable $e) {
            $quotation->update([
                'billing_status' => BillingStatus::Failed,
                'billing_error' => mb_substr($e->getMessage(), 0, 1000),
            ]);

            QuotationStatusLog::query()->create([
                'quotation_id' => $quotation->id,
                'from_status' => $quotation->status->value,
                'to_status' => $quotation->status->value,
                'user_id' => $actor?->id,
                'remarks' => 'Billing generation failed: '.mb_substr($e->getMessage(), 0, 500),
            ]);

            report($e);

            return ['ok' => false, 'error' => $e->getMessage(), 'invoices' => collect(), 'csns' => collect()];
        }

        $this->notifyCustomer($quotation->fresh(['customer']), $result['invoices'], $result['csns']);

        return ['ok' => true, 'error' => null, 'invoices' => $result['invoices'], 'csns' => $result['csns']];
    }

    /**
     * Cash orders: one Cash Bill per completed cash payment transaction (3 payments = 3 Cash Bills).
     * An admin release without a payment issues a single outstanding Cash Bill for the total.
     *
     * @return Collection<int, Invoice>
     */
    private function cashBills(Quotation $quotation): Collection
    {
        $payments = Payment::query()
            ->where('quotation_id', $quotation->id)
            ->where('status', 'completed')
            ->orderBy('id')
            ->get();

        $bills = collect();

        foreach ($payments as $payment) {
            $existing = Invoice::query()->where('payment_id', $payment->id)->first();

            if ($existing) {
                $bills->push($existing);

                continue;
            }

            $bills->push($this->createInvoice($quotation, 'cash_bill', (float) $payment->amount, InvoiceStatus::Paid, [
                ['description' => sprintf('Cash Bill — %s payment%s for order %s', ucfirst(str_replace('_', ' ', (string) $payment->method)), $payment->reference ? ' ref '.$payment->reference : '', $quotation->number), 'amount' => (float) $payment->amount],
            ], $payment));
        }

        if ($bills->isEmpty()) {
            $existing = $quotation->invoices->firstWhere('type', 'cash_bill');

            if ($existing) {
                return collect([$existing]);
            }

            if (! $quotation->isReleased()) {
                throw new InvalidArgumentException('No approved payment found for this cash order.');
            }

            $bills->push($this->createInvoice($quotation, 'cash_bill', (float) $quotation->total_amount, InvoiceStatus::Outstanding, $this->linesFromQuotation($quotation)));
        }

        return $bills;
    }

    /**
     * The COD / Term invoice of an order whose CSN already exists: a Term invoice on Admin's request, a COD
     * invoice once fully paid. Never duplicates an existing invoice of the order.
     */
    public function issueInvoice(Quotation $quotation, ?User $actor = null): Invoice
    {
        $quotation = $quotation->fresh(['customer', 'branch', 'lines', 'destinations', 'invoices', 'proformaInvoice']);
        $type = $quotation->orderType();

        if (! in_array($type, [OrderType::Cod, OrderType::Term], true)) {
            throw new InvalidArgumentException('Only COD and credit term orders get an invoice this way.');
        }

        $existing = $quotation->invoices->first(fn (Invoice $i) => $i->type === ($type === OrderType::Cod ? 'cod' : 'term') && $i->status !== 'cancelled');

        if ($existing) {
            return $existing;
        }

        $csn = $quotation->consignmentNotes()->where('status', '!=', 'cancelled')->orderBy('id')->first();

        if (! $csn) {
            throw new InvalidArgumentException('Create the CSN before issuing the invoice.');
        }

        $csnIds = $quotation->consignmentNotes()->where('status', '!=', 'cancelled')->pluck('id');
        $alreadyInvoiced = Invoice::query()->where('status', '!=', 'cancelled')
            ->whereHas('lines', fn ($q) => $q->whereIn('consignment_note_id', $csnIds))
            ->first();

        if ($alreadyInvoiced) {
            throw new InvalidArgumentException('The CSN of this order is already invoiced on '.$alreadyInvoiced->number.'.');
        }

        if ($type === OrderType::Cod && ! $this->isFullyPaid($quotation)) {
            throw new InvalidArgumentException('A COD invoice is issued once the order is fully paid.');
        }

        return DB::transaction(function () use ($quotation, $csn, $actor) {
            $invoice = $this->invoice($quotation)->first();
            $invoice->update(['consignment_note_id' => $csn->id]);
            $invoice->lines()->whereNull('consignment_note_id')->update(['consignment_note_id' => $csn->id]);
            Payment::query()->where('quotation_id', $quotation->id)->whereNull('invoice_id')->update(['invoice_id' => $invoice->id]);

            QuotationStatusLog::query()->create([
                'quotation_id' => $quotation->id,
                'from_status' => $quotation->status->value,
                'to_status' => $quotation->status->value,
                'user_id' => $actor?->id,
                'remarks' => 'Invoice issued: '.$invoice->number.' · RM '.number_format((float) $invoice->total_amount, 2),
            ]);

            return $invoice->fresh('lines');
        });
    }

    private function isFullyPaid(Quotation $quotation): bool
    {
        return RefreshOrderPaidAmount::livePaid($quotation) + 0.005 >= (float) $quotation->total_amount;
    }

    /** @return Collection<int, Invoice> */
    private function invoice(Quotation $quotation): Collection
    {
        $type = $quotation->orderType() === OrderType::Cod ? 'cod' : 'term';
        $existing = $quotation->invoices->firstWhere('type', $type);

        if ($existing) {
            return collect([$existing]);
        }

        $paid = RefreshOrderPaidAmount::livePaid($quotation);
        $status = $paid + 0.005 >= (float) $quotation->total_amount
            ? InvoiceStatus::Paid
            : ($paid > 0 ? InvoiceStatus::PartiallyPaid : InvoiceStatus::Outstanding);

        return collect([$this->createInvoice($quotation, $type, (float) $quotation->total_amount, $status, $this->linesFromQuotation($quotation))]);
    }

    /** @return list<array{description: string, amount: float}> */
    private function linesFromQuotation(Quotation $quotation): array
    {
        $lines = $quotation->lines
            ->filter(fn ($line) => (float) $line->line_total > 0)
            ->map(fn ($line) => [
                'description' => trim($line->item_name.' x '.rtrim(rtrim(number_format((float) $line->quantity, 3, '.', ''), '0'), '.').' '.($line->uom ?? '')),
                'amount' => (float) $line->line_total,
            ])
            ->values()
            ->all();

        return $lines !== [] ? $lines : [['description' => 'Transport charges — '.$quotation->number, 'amount' => (float) $quotation->total_amount]];
    }

    /** @param  list<array{description: string, amount: float}>  $lines */
    private function createInvoice(Quotation $quotation, string $type, float $total, InvoiceStatus $status, array $lines, ?Payment $payment = null): Invoice
    {
        $subtotal = round(collect($lines)->sum('amount'), 2);
        $rounded = round($total, 2);
        $dueDays = $type === 'term' ? (int) ($quotation->customer?->credit_term_days ?? 0) : 0;

        $invoice = Invoice::query()->create([
            'number' => $this->numbering->next($quotation->branch, DocumentType::Invoice),
            'company_id' => $quotation->company_id,
            'source_branch_id' => $quotation->branch_id,
            'customer_id' => $quotation->customer_id,
            'quotation_id' => $quotation->id,
            'proforma_invoice_id' => $quotation->proformaInvoice?->id,
            'payment_id' => $payment?->id,
            'type' => $type,
            'billing_month' => now()->format('Y-m'),
            'status' => $status->value,
            'subtotal' => $subtotal,
            'tax_amount' => 0,
            'rounding_amount' => round($rounded - $subtotal, 2),
            'total_amount' => $rounded,
            'invoice_date' => now()->toDateString(),
            'due_date' => now()->addDays($dueDays)->toDateString(),
        ]);

        foreach ($lines as $line) {
            $invoice->lines()->create(['description' => $line['description'], 'amount' => $line['amount']]);
        }

        if ($payment && ! $payment->invoice_id) {
            $payment->update(['invoice_id' => $invoice->id]);
        }

        return $invoice->load('lines');
    }

    private function notifyCustomer(Quotation $quotation, Collection $invoices, Collection $csns): void
    {
        $customer = $quotation->customer;
        $isCash = $quotation->orderType() === OrderType::Cash;

        // COD / Term without an invoice yet: the invoice gets its own email when it is issued
        if ($invoices->isEmpty()) {
            return;
        }

        $this->notify->execute(
            event: 'billing_issued',
            recipient: ['type' => 'customer', 'name' => $customer?->company_name, 'email' => $customer?->email, 'phone' => $customer?->phone],
            subject: ($isCash ? 'Cash Bill issued for ' : 'Invoice issued for ').$quotation->number,
            message: sprintf(
                "%s %s has been issued for order %s.\nConsignment note(s): %s\nYour delivery is now pending lorry assignment.",
                $isCash ? 'Cash Bill' : 'Invoice',
                $invoices->pluck('number')->implode(', '),
                $quotation->number,
                $csns->pluck('number')->implode(', ') ?: '—',
            ),
            related: $quotation,
        );
    }
}
