<?php

namespace App\Domains\Commission\Actions;

use App\Domains\Commission\Models\CommissionBatch;
use App\Domains\Commission\Models\CommissionLineItem;
use App\Domains\Commission\Models\CommissionSlip;
use App\Domains\Dispatch\Models\DeliveryOrder;
use App\Domains\MasterData\Models\Branch;
use App\Enums\DeliveryOrderStatus;
use App\Enums\DocumentType;
use App\Models\User;
use App\Services\DocumentNumberingService;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use InvalidArgumentException;

class GenerateCommissionBatch
{
    public function __construct(
        private DocumentNumberingService $numbering,
        private ResolveCommissionShares $shares,
    ) {}

    public function execute(Branch $branch, string $month, User $actor, ?Carbon $cutoff = null): CommissionBatch
    {
        if (! preg_match('/^\d{4}-\d{2}$/', $month)) {
            throw new InvalidArgumentException('Month must be YYYY-MM.');
        }

        $start = Carbon::createFromFormat('Y-m', $month)->startOfMonth();
        $end = $start->copy()->endOfMonth();
        $cutoff = $cutoff ?? $end->copy();

        return DB::transaction(function () use ($branch, $month, $actor, $start, $end, $cutoff) {
            $batch = CommissionBatch::query()->firstOrNew([
                'source_branch_id' => $branch->id,
                'month' => $month,
            ]);

            if ($batch->exists && $batch->status === 'confirmed') {
                throw new InvalidArgumentException('Commission batch for '.$month.' is already confirmed/locked.');
            }

            if (! $batch->exists) {
                $batch->number = $this->numbering->next($branch, DocumentType::CommissionBatch);
                $batch->status = 'draft';
            }

            $batch->fill([
                'cutoff_date' => $cutoff->toDateString(),
                'notes' => 'Generated by '.$actor->name.' at '.now()->toDateTimeString(),
            ])->save();

            // Rebuild draft slips
            $batch->slips()->each(function (CommissionSlip $slip) {
                $slip->lines()->delete();
                $slip->adjustments()->delete();
                $slip->purchaseOrder()?->delete();
                $slip->delete();
            });

            $orders = DeliveryOrder::query()
                ->with(['consignmentNote.returnedCsn', 'lorry', 'driver', 'failedDelivery', 'subsheets'])
                ->where('source_branch_id', $branch->id)
                ->where(function ($q) use ($start, $end) {
                    $q->whereBetween('delivered_at', [$start, $end])
                        ->orWhereBetween('failed_at', [$start, $end]);
                })
                ->whereIn('status', [
                    DeliveryOrderStatus::Delivered->value,
                    DeliveryOrderStatus::Failed->value,
                    DeliveryOrderStatus::Reassigned->value,
                ])
                ->get();

            // Include prior carry-forward ineligible lines released this month (CSN now returned)
            $carryForward = CommissionLineItem::query()
                ->with(['deliveryOrder.consignmentNote', 'slip'])
                ->where('is_carry_forward', true)
                ->where('is_eligible', true)
                ->whereHas('slip', fn ($q) => $q->where('source_branch_id', $branch->id))
                ->whereHas('slip.batch', fn ($q) => $q->where('status', 'confirmed')->where('month', '<', $month))
                ->get();

            /** @var array<int, array{slip: CommissionSlip, psi: float, pso: float}> $slipMap */
            $slipMap = [];

            $ensureSlip = function (?int $driverId, ?int $lorryId) use (&$slipMap, $batch, $branch) {
                if (! $driverId) {
                    return null;
                }
                if (! isset($slipMap[$driverId])) {
                    $slip = CommissionSlip::query()->create([
                        'number' => $this->numbering->next($branch, DocumentType::CommissionSlip),
                        'commission_batch_id' => $batch->id,
                        'source_branch_id' => $branch->id,
                        'driver_id' => $driverId,
                        'lorry_id' => $lorryId,
                        'system_amount' => 0,
                        'final_amount' => 0,
                        'psi_amount' => 0,
                        'pso_amount' => 0,
                        'deductions' => 0,
                        'status' => 'draft',
                    ]);
                    $slipMap[$driverId] = ['slip' => $slip, 'psi' => 0.0, 'pso' => 0.0];
                }

                return $slipMap[$driverId]['slip'];
            };

            foreach ($orders as $do) {
                foreach ($this->shares->execute($do) as $share) {
                    $slip = $ensureSlip($share['driver_id'], $share['lorry_id']);
                    if (! $slip) {
                        continue;
                    }

                    $eligible = $share['is_eligible'];
                    $carry = ! $eligible;

                    CommissionLineItem::query()->create([
                        'commission_slip_id' => $slip->id,
                        'delivery_order_id' => $do->id,
                        'consignment_note_id' => $do->consignment_note_id,
                        'driver_id' => $share['driver_id'],
                        'lorry_id' => $share['lorry_id'],
                        'amount' => $share['amount'],
                        'split_percent' => $share['split_percent'],
                        'line_type' => $share['line_type'],
                        'is_eligible' => $eligible,
                        'is_hidden' => false,
                        'is_carry_forward' => $carry,
                        'notes' => $share['notes'],
                    ]);

                    if ($share['line_type'] === 'psi') {
                        $slipMap[$share['driver_id']]['psi'] += $share['amount'];
                    }
                    if ($share['line_type'] === 'pso') {
                        $slipMap[$share['driver_id']]['pso'] += $share['amount'];
                    }
                }
            }

            foreach ($carryForward as $old) {
                $slip = $ensureSlip($old->driver_id ?? $old->slip->driver_id, $old->lorry_id);
                if (! $slip) {
                    continue;
                }

                CommissionLineItem::query()->create([
                    'commission_slip_id' => $slip->id,
                    'delivery_order_id' => $old->delivery_order_id,
                    'consignment_note_id' => $old->consignment_note_id,
                    'driver_id' => $old->driver_id,
                    'lorry_id' => $old->lorry_id,
                    'amount' => $old->amount,
                    'split_percent' => $old->split_percent,
                    'line_type' => 'carry_forward',
                    'is_eligible' => true,
                    'is_hidden' => false,
                    'is_carry_forward' => false,
                    'notes' => 'Released carry-forward from '.$old->slip->batch?->month,
                ]);

                $old->update(['is_carry_forward' => false]);
            }

            foreach ($slipMap as $driverId => $entry) {
                /** @var CommissionSlip $slip */
                $slip = $entry['slip'];
                $system = (float) $slip->lines()->where('is_hidden', false)->sum('amount');
                $eligible = (float) $slip->lines()
                    ->where('is_hidden', false)
                    ->where('is_eligible', true)
                    ->sum('amount');

                $slip->update([
                    'system_amount' => $system,
                    'final_amount' => $eligible,
                    'psi_amount' => $entry['psi'],
                    'pso_amount' => $entry['pso'],
                    'deductions' => 0,
                ]);
            }

            return $batch->fresh(['slips.lines', 'slips.driver', 'sourceBranch']);
        });
    }
}
